# Generated by Django 3.0.7 on 2021-07-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=5, null=True)),
                ('bank', models.CharField(blank=True, max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('deactivated', models.BooleanField(default=False)),
                ('assigned_buckets', models.CharField(blank=True, max_length=40, null=True)),
                ('registration_authenticated', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('age_wise_category_list', models.CharField(blank=True, default="['0','18','30','40','65']", max_length=100, null=True)),
                ('income_wise_category_list', models.CharField(blank=True, default="['7000','15000','20000','35000','50000']", max_length=100, null=True)),
                ('outstanding_wise_category_list', models.CharField(blank=True, default="['100','1000','2000','4000','6000']", max_length=100, null=True)),
                ('reporting_manager_name', models.CharField(blank=True, max_length=20, null=True)),
                ('reporting_manager_email', models.CharField(blank=True, max_length=20, null=True)),
                ('linked_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_by_admin', to='Log.Account')),
                ('linked_fcm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fcm', to='Log.Account')),
                ('linked_vcm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_vcm', to='Log.Account')),
                ('linked_vit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_vit', to='Log.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
