# Generated by Django 3.0.7 on 2021-07-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='assigned_buckets',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deactivated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='linked_admin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='linked_fcm',
        ),
        migrations.RemoveField(
            model_name='account',
            name='linked_vcm',
        ),
        migrations.RemoveField(
            model_name='account',
            name='linked_vit',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
