# Generated by Django 3.0.7 on 2021-07-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0003_auto_20210729_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age_wise_category_list',
        ),
        migrations.RemoveField(
            model_name='account',
            name='income_wise_category_list',
        ),
        migrations.RemoveField(
            model_name='account',
            name='outstanding_wise_category_list',
        ),
    ]
