# Generated by Django 3.0.7 on 2021-07-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0004_auto_20210729_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
