# Generated by Django 3.0.7 on 2021-07-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0005_remove_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='account',
            name='registration_authenticated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reporting_manager_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reporting_manager_name',
        ),
    ]
