# Generated by Django 3.0.7 on 2021-07-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0006_auto_20210729_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
