# Generated by Django 3.0.7 on 2021-07-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0007_auto_20210729_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
