# Generated by Django 3.0.7 on 2021-07-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0008_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='staff_id',
        ),
    ]
