# Generated by Django 3.0.7 on 2021-07-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0010_account_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
